version: '3.2'
services:
  mysql:
    image: mysql:5.7.22
    container_name: health_now
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_DATABASE: HealthNow
    ports:
      - 3306:3306
    networks:
      - local
networks:
  local:
    driver: bridge
